// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCV0bMGnTqZQlPJ21UltmhoRs1GMnRXkrU',
    appId: '1:207955267399:web:11e103f3f3e6b1a350c662',
    messagingSenderId: '207955267399',
    projectId: 'flashcards-flutter-andrew',
    authDomain: 'flashcards-flutter-andrew.firebaseapp.com',
    storageBucket: 'flashcards-flutter-andrew.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0cARAA25vJ7GQsISAdZY2pDe9rnQeSMw',
    appId: '1:207955267399:android:0f464a5643ef03cd50c662',
    messagingSenderId: '207955267399',
    projectId: 'flashcards-flutter-andrew',
    storageBucket: 'flashcards-flutter-andrew.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEqTw9ItAT_4__ns8aRc7RJcEaXZigaMs',
    appId: '1:207955267399:ios:6e172d58e17cd9a450c662',
    messagingSenderId: '207955267399',
    projectId: 'flashcards-flutter-andrew',
    storageBucket: 'flashcards-flutter-andrew.appspot.com',
    iosBundleId: 'com.example.noteCardApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEqTw9ItAT_4__ns8aRc7RJcEaXZigaMs',
    appId: '1:207955267399:ios:6e172d58e17cd9a450c662',
    messagingSenderId: '207955267399',
    projectId: 'flashcards-flutter-andrew',
    storageBucket: 'flashcards-flutter-andrew.appspot.com',
    iosBundleId: 'com.example.noteCardApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCV0bMGnTqZQlPJ21UltmhoRs1GMnRXkrU',
    appId: '1:207955267399:web:4cb1950ced53756550c662',
    messagingSenderId: '207955267399',
    projectId: 'flashcards-flutter-andrew',
    authDomain: 'flashcards-flutter-andrew.firebaseapp.com',
    storageBucket: 'flashcards-flutter-andrew.appspot.com',
  );

}